mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Flavour_Counter__c</fullName>
        <label>Flavour Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ice_Cream_Flavours__c</fullName>
        <label>Ice Cream Flavours</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chocolate</fullName>
                </value>
                <value>
                    <fullName>Vanilla</fullName>
                </value>
                <value>
                    <fullName>Strawberry</fullName>
                </value>
                <value>
                    <fullName>Amarena</fullName>
                </value>
                <value>
                    <fullName>Stracciatella</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapipkg/classes/MultiSelectPicklistChoiceCounterTest.cls
@isTest
public class MultiSelectPicklistChoiceCounterTest {
	
    @isTest static void createAccount() {
        Account acc = new Account();
        acc.Name = 'Test';
        // The created account has to have at least one ice cream flavour selected for all lines of code to run
        acc.Ice_Cream_Flavours__c = 'Strawberry;Chocolate';
        insert acc;

        // Check if the counter is correct
        Account checkAccount = [SELECT Flavour_Counter__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(2, checkAccount.Flavour_Counter__c, 'Multi-select counter not resulting in correct number');
    }
}