mdapipkg/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor_1_Price__c</fullName>
        <label>Competitor 1 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_1__c</fullName>
        <label>Competitor 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Companies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor_2_Price__c</fullName>
        <label>Competitor 2 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_2__c</fullName>
        <label>Competitor 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Companies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor_3_Price__c</fullName>
        <label>Competitor 3 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_3__c</fullName>
        <label>Competitor 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Companies</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Leading_Competitor__c</fullName>
        <label>Leading Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Companies</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapi/unpackaged/globalValueSets/Competitor_Companies.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo!</fullName>
    </customValue>
    <masterLabel>Competitor Companies</masterLabel>
</GlobalValueSet>

mdapi/unpackaged/classes/LeadingCompetitorTest.cls
@isTest
public class LeadingCompetitorTest {
	
    @isTest static void createOpp() {
        Opportunity opp = new Opportunity();
        
        // Required fields
        opp.Name = 'Test';
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospecting';

        // Populate price fields
        opp.Competitor_1_Price__c = 1;
        opp.Competitor_2_Price__c = 2;
        opp.Competitor_3_Price__c = 3;

        // Populate name fields
        opp.Competitor_1__c = 'Amazon';
        opp.Competitor_2__c = 'Google';
        opp.Competitor_3__c = 'Microsoft';

        // Insert opportunity
        insert opp;
        
        // Check if leading competitor was filled out correctly
        Opportunity insertedOpp = [SELECT Leading_Competitor__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Amazon', insertedOpp.Leading_Competitor__c, 'Leading competitor incorrect');


    }
}